/**
 * Auto-reorder service. Loads inventory state from the DB, runs the
 * pure engine in `./reorder.ts`, and creates draft purchase orders
 * grouped by supplier.
 *
 * Called from a job handler keyed `inventory.reorder.scan` (registered in
 * the queue worker) so it can be triggered manually, by cron, or after a
 * stock-out movement.
 */

import "server-only";
import { prisma } from "@/lib/prisma";
import { recordAuditEvent } from "@/modules/audit/record";
import {
  REORDER_JOB_KIND,
  findItemsNeedingReorder,
  groupBySupplier,
  type ReorderItem,
  type StockSnapshot,
} from "./reorder";

export type AutoReorderResult = {
  workspaceId: string;
  scannedItems: number;
  suggestionsCount: number;
  posCreated: { number: string; supplierId: string; total: number }[];
  /** Items that need reorder but have no preferred supplier set. */
  unassigned: { itemId: string; sku: string; shortBy: number }[];
};

export async function runAutoReorder(workspaceId: string): Promise<AutoReorderResult> {
  const items = await prisma.inventoryItem.findMany({
    where: { workspaceId, trackStock: true, reorderPoint: { gt: 0 } },
    select: {
      id: true,
      sku: true,
      name: true,
      reorderPoint: true,
      costPrice: true,
      product: { select: { id: true } },
    },
  });

  // Map of itemId → preferredSupplierId (via Product.suppliers if defined),
  // falling back to the first supplier in the workspace if none.
  const [defaultWh, suppliers] = await Promise.all([
    prisma.warehouse.findFirst({
      where: { workspaceId, isDefault: true },
      select: { id: true },
    }),
    prisma.supplier.findMany({ where: { workspaceId }, select: { id: true } }),
  ]);
  const fallbackSupplierId = suppliers[0]?.id ?? null;

  const reorderItems: ReorderItem[] = items.map((it) => ({
    id: it.id,
    sku: it.sku,
    name: it.name,
    reorderPoint: it.reorderPoint,
    costPrice: Number(it.costPrice),
    preferredSupplierId: fallbackSupplierId,
    defaultWarehouseId: defaultWh?.id ?? null,
  }));

  const stock: StockSnapshot[] = (
    await prisma.stockLevel.findMany({
      where: { item: { workspaceId } },
      select: { itemId: true, warehouseId: true, quantity: true },
    })
  ).map((s) => ({ itemId: s.itemId, warehouseId: s.warehouseId, quantity: s.quantity }));

  const suggestions = findItemsNeedingReorder(reorderItems, stock);
  const groups = groupBySupplier(suggestions);

  const result: AutoReorderResult = {
    workspaceId,
    scannedItems: items.length,
    suggestionsCount: suggestions.length,
    posCreated: [],
    unassigned: [],
  };

  for (const group of groups) {
    if (!group.supplierId) {
      for (const s of group.suggestions) {
        const item = items.find((i) => i.id === s.itemId);
        result.unassigned.push({
          itemId: s.itemId,
          sku: item?.sku ?? "",
          shortBy: s.shortBy,
        });
      }
      continue;
    }
    const number = await nextPoNumberForWorkspace(workspaceId);
    const subtotal = group.suggestions.reduce(
      (sum, s) => sum + s.unitCost * s.suggestedQty,
      0,
    );
    const po = await prisma.purchaseOrder.create({
      data: {
        workspaceId,
        number,
        supplierId: group.supplierId,
        status: "DRAFT",
        orderDate: new Date(),
        currency: "USD",
        subtotal,
        tax: 0,
        total: subtotal,
        notes: "Auto-generated by reorder scan",
        lines: {
          create: group.suggestions
            .filter((s) => s.warehouseId)
            .map((s) => {
              const item = items.find((i) => i.id === s.itemId)!;
              return {
                itemId: s.itemId,
                warehouseId: s.warehouseId,
                description: item.name,
                qtyOrdered: s.suggestedQty,
                qtyReceived: 0,
                unitCost: s.unitCost,
                taxPercent: 0,
                amount: Number((s.unitCost * s.suggestedQty).toFixed(2)),
              };
            }),
        },
      },
      select: { number: true, supplierId: true, total: true },
    });
    result.posCreated.push({
      number: po.number,
      supplierId: po.supplierId,
      total: Number(po.total),
    });
  }

  if (result.posCreated.length > 0) {
    await recordAuditEvent({
      workspaceId,
      actorId: null,
      action: "create",
      resource: "purchaseOrder",
      resourceId: result.posCreated.map((p) => p.number).join(","),
      meta: { kind: "auto-reorder", count: result.posCreated.length },
    });
  }

  return result;
}

async function nextPoNumberForWorkspace(workspaceId: string): Promise<string> {
  const latest = await prisma.purchaseOrder.findFirst({
    where: { workspaceId },
    orderBy: { createdAt: "desc" },
    select: { number: true },
  });
  const n = latest ? parseInt(latest.number.replace(/\D/g, ""), 10) || 0 : 0;
  return `PO-${String(n + 1).padStart(5, "0")}`;
}

export { REORDER_JOB_KIND };
