/**
 * OmniSuite permission system.
 *
 * Permissions are tuples of (resource, action). Roles are static maps from
 * resource → set of allowed actions. Resolution is server-authoritative; the
 * client hook is a convenience for hiding UI affordances.
 */
import type { SystemRole } from "@prisma/client";

export const RESOURCES = [
  "contact",
  "company",
  "lead",
  "deal",
  "pipeline",
  "invoice",
  "customer",
  "product",
  "project",
  "task",
  "ticket",
  "form",
  "campaign",
  "audience",
  "report",
  "auditLog",
  "warehouse",
  "inventoryItem",
  "supplier",
  "purchaseOrder",
  "expense",
  "expenseCategory",
  "employee",
  "department",
  "leaveType",
  "leaveRequest",
  "signatureEnvelope",
  "bookingType",
  "booking",
  "issueProject",
  "issue",
  "issueComment",
  "chatConversation",
  "chatMessage",
  "workflow",
  "workflowEnrollment",
  "mailThread",
  "mailMessage",
  "ledgerAccount",
  "journalEntry",
  "bankAccount",
  "bankTransaction",
  "jobOpening",
  "candidate",
  "application",
  "interview",
  "folder",
  "fileAsset",
  "subscriptionPlan",
  "subscription",
  "subscriptionInvoice",
  "dashboard",
  "dashboardWidget",
  "survey",
  "surveyResponse",
  "pivotReport",
  "notebook",
  "note",
  "vaultFolder",
  "vaultItem",
  "event",
  "eventRegistration",
  "teamChannel",
  "teamMessage",
  "site",
  "sitePage",
  "socialAccount",
  "socialPost",
  "connectGroup",
  "connectPost",
  "connectComment",
  "leadScoreRule",
  "leadScoreEvent",
  "experiment",
  "experimentEvent",
  "course",
  "lesson",
  "courseEnrollment",
  "payRun",
  "paySlip",
  "asset",
  "change",
  "problem",
  "storefront",
  "storeCustomer",
  "storeOrder",
  "ssoProvider",
  "ssoLoginEvent",
  "heatmapSite",
  "heatmapPage",
  "heatmapEvent",
  "sessionRecording",
  "flow",
  "flowRun",
  "flowApproval",
  "creatorApp",
  "creatorRecord",
  "writerDoc",
  "sheet",
  "presentation",
  "kbArticle",
  "gantt",
  "timeEntry",
  "careerSite",
  "settings.workspace",
  "settings.users",
  "settings.billing",
  "settings.security",
  "settings.apiKeys",
  "settings.webhooks",
] as const;

export type Resource = (typeof RESOURCES)[number];

export const ACTIONS = [
  "view",
  "create",
  "edit",
  "delete",
  "export",
  "assign",
  "send",
  "manage",
] as const;

export type Action = (typeof ACTIONS)[number];

const ALL: readonly Action[] = ACTIONS;
const READ_ONLY: readonly Action[] = ["view"];
const READ_WRITE: readonly Action[] = ["view", "create", "edit"];
const READ_WRITE_DELETE: readonly Action[] = ["view", "create", "edit", "delete", "export"];

type RoleMatrix = Record<Resource, readonly Action[]>;

/** Owner can do anything. */
const ownerMatrix: RoleMatrix = Object.fromEntries(
  RESOURCES.map((r) => [r, ALL]),
) as RoleMatrix;

/** Admin: everything except destructive workspace ops are equivalent to Owner in MVP. */
const adminMatrix: RoleMatrix = ownerMatrix;

/** Manager: full operational control, can't change billing/users. */
const managerMatrix: RoleMatrix = {
  ...ownerMatrix,
  ssoProvider: READ_ONLY,
  ssoLoginEvent: READ_ONLY,
  heatmapSite: READ_WRITE_DELETE,
  heatmapPage: READ_WRITE_DELETE,
  heatmapEvent: READ_ONLY,
  sessionRecording: READ_WRITE_DELETE,
  flow: READ_WRITE_DELETE,
  flowRun: [...READ_WRITE_DELETE, "manage"],
  flowApproval: [...READ_ONLY, "manage"],
  creatorApp: READ_WRITE_DELETE,
  creatorRecord: READ_WRITE_DELETE,
  writerDoc: READ_WRITE_DELETE,
  sheet: READ_WRITE_DELETE,
  presentation: READ_WRITE_DELETE,
  kbArticle: READ_WRITE_DELETE,
  gantt: READ_WRITE_DELETE,
  timeEntry: [...READ_WRITE_DELETE, "manage"],
  careerSite: [...READ_WRITE_DELETE, "manage"],
  "settings.workspace": READ_ONLY,
  "settings.users": ["view"],
  "settings.billing": READ_ONLY,
  "settings.security": READ_ONLY,
  "settings.apiKeys": READ_ONLY,
  "settings.webhooks": READ_ONLY,
};

/** Sales rep: full CRM/Sales, read-only on the rest. */
const salesMatrix: RoleMatrix = {
  contact: READ_WRITE_DELETE,
  company: READ_WRITE_DELETE,
  lead: [...READ_WRITE_DELETE, "assign"],
  deal: [...READ_WRITE_DELETE, "assign"],
  pipeline: READ_ONLY,
  invoice: READ_WRITE,
  customer: READ_WRITE,
  product: READ_ONLY,
  project: READ_ONLY,
  task: READ_WRITE,
  ticket: READ_ONLY,
  form: READ_ONLY,
  campaign: READ_ONLY,
  audience: READ_ONLY,
  report: READ_ONLY,
  auditLog: [],
  warehouse: READ_ONLY,
  inventoryItem: READ_ONLY,
  supplier: READ_ONLY,
  purchaseOrder: [],
  expense: READ_WRITE,
  expenseCategory: READ_ONLY,
  employee: READ_ONLY,
  department: READ_ONLY,
  leaveType: READ_ONLY,
  leaveRequest: READ_WRITE,
  signatureEnvelope: READ_WRITE,
  bookingType: READ_WRITE,
  booking: READ_WRITE_DELETE,
  issueProject: READ_ONLY,
  issue: [...READ_WRITE_DELETE, "assign"],
  issueComment: READ_WRITE,
  chatConversation: [...READ_WRITE_DELETE, "assign"],
  chatMessage: [...READ_WRITE, "send"],
  workflow: [...READ_WRITE_DELETE, "manage"],
  workflowEnrollment: [...READ_WRITE_DELETE, "manage"],
  mailThread: READ_WRITE_DELETE,
  mailMessage: [...READ_WRITE, "send"],
  ledgerAccount: [],
  journalEntry: [],
  bankAccount: [],
  bankTransaction: [],
  jobOpening: READ_ONLY,
  candidate: READ_WRITE,
  application: READ_ONLY,
  interview: READ_ONLY,
  folder: READ_WRITE,
  fileAsset: READ_WRITE_DELETE,
  subscriptionPlan: READ_ONLY,
  subscription: READ_WRITE,
  subscriptionInvoice: READ_ONLY,
  dashboard: READ_WRITE_DELETE,
  dashboardWidget: READ_WRITE_DELETE,
  survey: READ_ONLY,
  surveyResponse: READ_ONLY,
  pivotReport: READ_ONLY,
  notebook: READ_WRITE,
  note: READ_WRITE_DELETE,
  vaultFolder: READ_WRITE,
  vaultItem: READ_WRITE,
  event: READ_WRITE,
  eventRegistration: READ_WRITE,
  teamChannel: READ_WRITE,
  teamMessage: READ_WRITE_DELETE,
  site: READ_ONLY,
  sitePage: READ_ONLY,
  socialAccount: READ_ONLY,
  socialPost: READ_WRITE,
  connectGroup: READ_ONLY,
  connectPost: READ_WRITE,
  connectComment: READ_WRITE_DELETE,
  leadScoreRule: READ_ONLY,
  leadScoreEvent: READ_WRITE,
  experiment: READ_ONLY,
  experimentEvent: READ_WRITE,
  course: READ_ONLY,
  lesson: READ_ONLY,
  courseEnrollment: READ_ONLY,
  payRun: [],
  paySlip: [],
  asset: READ_ONLY,
  change: READ_ONLY,
  problem: READ_ONLY,
  storefront: READ_ONLY,
  storeCustomer: READ_WRITE_DELETE,
  storeOrder: [...READ_WRITE_DELETE, "manage"],
  ssoProvider: [],
  ssoLoginEvent: [],
  heatmapSite: READ_ONLY,
  heatmapPage: READ_ONLY,
  heatmapEvent: READ_ONLY,
  sessionRecording: READ_ONLY,
  flow: READ_ONLY,
  flowRun: READ_ONLY,
  flowApproval: [],
  creatorApp: READ_ONLY,
  creatorRecord: READ_ONLY,
  writerDoc: READ_ONLY,
  sheet: READ_ONLY,
  presentation: READ_ONLY,
  kbArticle: READ_ONLY,
  gantt: READ_ONLY,
  timeEntry: READ_ONLY,
  careerSite: READ_ONLY,
  "settings.workspace": [],
  "settings.users": [],
  "settings.billing": [],
  "settings.security": [],
  "settings.apiKeys": [],
  "settings.webhooks": [],
};

/** Finance: full billing, read CRM. */
const financeMatrix: RoleMatrix = {
  contact: READ_ONLY,
  company: READ_ONLY,
  lead: [],
  deal: READ_ONLY,
  pipeline: [],
  invoice: [...READ_WRITE_DELETE, "send"],
  customer: READ_WRITE_DELETE,
  product: READ_WRITE_DELETE,
  project: READ_ONLY,
  task: [],
  ticket: [],
  form: [],
  campaign: [],
  audience: [],
  report: READ_ONLY,
  auditLog: READ_ONLY,
  warehouse: READ_WRITE_DELETE,
  inventoryItem: READ_WRITE_DELETE,
  supplier: READ_WRITE_DELETE,
  purchaseOrder: [...READ_WRITE_DELETE, "send"],
  expense: [...READ_WRITE_DELETE, "manage"],
  expenseCategory: READ_WRITE_DELETE,
  employee: READ_ONLY,
  department: READ_ONLY,
  leaveType: READ_ONLY,
  leaveRequest: READ_ONLY,
  signatureEnvelope: READ_ONLY,
  bookingType: READ_ONLY,
  booking: READ_ONLY,
  issueProject: [],
  issue: [],
  issueComment: [],
  chatConversation: [],
  chatMessage: [],
  workflow: [],
  workflowEnrollment: [],
  mailThread: READ_ONLY,
  mailMessage: READ_ONLY,
  ledgerAccount: READ_WRITE_DELETE,
  journalEntry: [...READ_WRITE_DELETE, "manage"],
  bankAccount: READ_WRITE_DELETE,
  bankTransaction: [...READ_WRITE_DELETE, "manage"],
  jobOpening: READ_ONLY,
  candidate: READ_ONLY,
  application: READ_ONLY,
  interview: READ_ONLY,
  folder: READ_WRITE,
  fileAsset: READ_WRITE_DELETE,
  subscriptionPlan: READ_WRITE_DELETE,
  subscription: [...READ_WRITE_DELETE, "manage"],
  subscriptionInvoice: [...READ_WRITE_DELETE, "send"],
  dashboard: READ_WRITE_DELETE,
  dashboardWidget: READ_WRITE_DELETE,
  survey: READ_ONLY,
  surveyResponse: READ_ONLY,
  pivotReport: READ_ONLY,
  notebook: READ_WRITE,
  note: READ_WRITE_DELETE,
  vaultFolder: READ_ONLY,
  vaultItem: READ_ONLY,
  event: READ_ONLY,
  eventRegistration: READ_ONLY,
  teamChannel: READ_WRITE,
  teamMessage: READ_WRITE_DELETE,
  site: READ_ONLY,
  sitePage: READ_ONLY,
  socialAccount: READ_ONLY,
  socialPost: READ_ONLY,
  connectGroup: READ_ONLY,
  connectPost: READ_WRITE,
  connectComment: READ_WRITE_DELETE,
  leadScoreRule: [],
  leadScoreEvent: [],
  experiment: [],
  experimentEvent: [],
  course: [],
  lesson: [],
  courseEnrollment: [],
  payRun: [...READ_WRITE_DELETE, "manage"],
  paySlip: READ_WRITE_DELETE,
  asset: READ_ONLY,
  change: READ_ONLY,
  problem: READ_ONLY,
  storefront: READ_ONLY,
  storeCustomer: READ_WRITE,
  storeOrder: [...READ_WRITE_DELETE, "manage"],
  ssoProvider: [],
  ssoLoginEvent: [],
  heatmapSite: READ_ONLY,
  heatmapPage: READ_ONLY,
  heatmapEvent: READ_ONLY,
  sessionRecording: READ_ONLY,
  flow: READ_ONLY,
  flowRun: READ_ONLY,
  flowApproval: [],
  creatorApp: READ_ONLY,
  creatorRecord: READ_ONLY,
  writerDoc: READ_ONLY,
  sheet: READ_ONLY,
  presentation: READ_ONLY,
  kbArticle: READ_ONLY,
  gantt: READ_ONLY,
  timeEntry: READ_ONLY,
  careerSite: READ_ONLY,
  "settings.workspace": READ_ONLY,
  "settings.users": [],
  "settings.billing": [...ALL],
  "settings.security": [],
  "settings.apiKeys": [],
  "settings.webhooks": [],
};

/** Helpdesk agent: tickets, contacts. */
const agentMatrix: RoleMatrix = {
  contact: READ_WRITE,
  company: READ_ONLY,
  lead: [],
  deal: [],
  pipeline: [],
  invoice: [],
  customer: READ_ONLY,
  product: [],
  project: [],
  task: READ_WRITE,
  ticket: [...READ_WRITE_DELETE, "assign", "send"],
  form: READ_ONLY,
  campaign: [],
  audience: [],
  report: READ_ONLY,
  auditLog: [],
  warehouse: [],
  inventoryItem: [],
  supplier: [],
  purchaseOrder: [],
  expense: READ_WRITE,
  expenseCategory: READ_ONLY,
  employee: READ_ONLY,
  department: READ_ONLY,
  leaveType: READ_ONLY,
  leaveRequest: READ_WRITE,
  signatureEnvelope: READ_WRITE,
  bookingType: READ_WRITE,
  booking: READ_WRITE_DELETE,
  issueProject: READ_ONLY,
  issue: [...READ_WRITE_DELETE, "assign"],
  issueComment: READ_WRITE,
  chatConversation: [...READ_WRITE_DELETE, "assign"],
  chatMessage: [...READ_WRITE, "send"],
  workflow: READ_ONLY,
  workflowEnrollment: READ_ONLY,
  mailThread: READ_WRITE_DELETE,
  mailMessage: [...READ_WRITE, "send"],
  ledgerAccount: [],
  journalEntry: [],
  bankAccount: [],
  bankTransaction: [],
  jobOpening: READ_ONLY,
  candidate: READ_ONLY,
  application: READ_ONLY,
  interview: READ_ONLY,
  folder: READ_WRITE,
  fileAsset: READ_WRITE,
  subscriptionPlan: READ_ONLY,
  subscription: READ_ONLY,
  subscriptionInvoice: READ_ONLY,
  dashboard: READ_ONLY,
  dashboardWidget: READ_ONLY,
  survey: READ_ONLY,
  surveyResponse: READ_ONLY,
  pivotReport: READ_ONLY,
  notebook: READ_WRITE,
  note: READ_WRITE_DELETE,
  vaultFolder: READ_ONLY,
  vaultItem: READ_ONLY,
  event: READ_ONLY,
  eventRegistration: READ_WRITE,
  teamChannel: READ_WRITE,
  teamMessage: READ_WRITE_DELETE,
  site: READ_ONLY,
  sitePage: READ_ONLY,
  socialAccount: READ_ONLY,
  socialPost: READ_ONLY,
  connectGroup: READ_ONLY,
  connectPost: READ_WRITE,
  connectComment: READ_WRITE_DELETE,
  leadScoreRule: [],
  leadScoreEvent: [],
  experiment: [],
  experimentEvent: [],
  course: [],
  lesson: [],
  courseEnrollment: [],
  payRun: [],
  paySlip: [],
  asset: [...READ_WRITE_DELETE, "assign"],
  change: [...READ_WRITE_DELETE, "manage"],
  problem: [...READ_WRITE_DELETE, "assign"],
  storefront: [],
  storeCustomer: [],
  storeOrder: [],
  ssoProvider: [],
  ssoLoginEvent: [],
  heatmapSite: [],
  heatmapPage: [],
  heatmapEvent: [],
  sessionRecording: [],
  flow: [],
  flowRun: [],
  flowApproval: [],
  creatorApp: [],
  creatorRecord: [],
  writerDoc: [],
  sheet: [],
  presentation: [],
  kbArticle: READ_ONLY,
  gantt: [],
  timeEntry: READ_WRITE,
  careerSite: [],
  "settings.workspace": [],
  "settings.users": [],
  "settings.billing": [],
  "settings.security": [],
  "settings.apiKeys": [],
  "settings.webhooks": [],
};

/** Member: standard contributor across modules. */
const memberMatrix: RoleMatrix = {
  contact: READ_WRITE,
  company: READ_WRITE,
  lead: READ_WRITE,
  deal: READ_WRITE,
  pipeline: READ_ONLY,
  invoice: READ_ONLY,
  customer: READ_ONLY,
  product: READ_ONLY,
  project: READ_WRITE,
  task: READ_WRITE_DELETE,
  ticket: READ_WRITE,
  form: READ_ONLY,
  campaign: READ_ONLY,
  audience: READ_ONLY,
  report: READ_ONLY,
  auditLog: [],
  warehouse: READ_ONLY,
  inventoryItem: READ_WRITE,
  supplier: READ_ONLY,
  purchaseOrder: READ_ONLY,
  expense: READ_WRITE_DELETE,
  expenseCategory: READ_ONLY,
  employee: READ_ONLY,
  department: READ_ONLY,
  leaveType: READ_ONLY,
  leaveRequest: READ_WRITE,
  signatureEnvelope: READ_WRITE,
  bookingType: READ_ONLY,
  booking: READ_WRITE,
  issueProject: READ_WRITE,
  issue: [...READ_WRITE_DELETE, "assign"],
  issueComment: READ_WRITE,
  chatConversation: READ_WRITE,
  chatMessage: [...READ_ONLY, "send"],
  workflow: READ_WRITE,
  workflowEnrollment: READ_WRITE,
  mailThread: READ_WRITE_DELETE,
  mailMessage: [...READ_WRITE, "send"],
  ledgerAccount: READ_ONLY,
  journalEntry: READ_ONLY,
  bankAccount: READ_ONLY,
  bankTransaction: READ_ONLY,
  jobOpening: [...READ_WRITE_DELETE, "manage"],
  candidate: READ_WRITE_DELETE,
  application: [...READ_WRITE_DELETE, "assign", "manage"],
  interview: READ_WRITE_DELETE,
  folder: READ_WRITE_DELETE,
  fileAsset: READ_WRITE_DELETE,
  subscriptionPlan: READ_ONLY,
  subscription: READ_WRITE,
  subscriptionInvoice: READ_ONLY,
  dashboard: READ_WRITE_DELETE,
  dashboardWidget: READ_WRITE_DELETE,
  survey: READ_WRITE_DELETE,
  surveyResponse: READ_ONLY,
  pivotReport: READ_WRITE_DELETE,
  notebook: READ_WRITE_DELETE,
  note: READ_WRITE_DELETE,
  vaultFolder: READ_WRITE_DELETE,
  vaultItem: READ_WRITE_DELETE,
  event: READ_WRITE_DELETE,
  eventRegistration: READ_WRITE_DELETE,
  teamChannel: READ_WRITE_DELETE,
  teamMessage: READ_WRITE_DELETE,
  site: READ_WRITE_DELETE,
  sitePage: READ_WRITE_DELETE,
  socialAccount: READ_WRITE_DELETE,
  socialPost: [...READ_WRITE_DELETE, "send"],
  connectGroup: READ_WRITE,
  connectPost: READ_WRITE_DELETE,
  connectComment: READ_WRITE_DELETE,
  leadScoreRule: READ_WRITE,
  leadScoreEvent: READ_WRITE_DELETE,
  experiment: READ_WRITE,
  experimentEvent: READ_WRITE_DELETE,
  course: READ_WRITE_DELETE,
  lesson: READ_WRITE_DELETE,
  courseEnrollment: READ_WRITE_DELETE,
  payRun: READ_WRITE,
  paySlip: READ_WRITE,
  asset: READ_WRITE_DELETE,
  change: READ_WRITE_DELETE,
  problem: READ_WRITE_DELETE,
  storefront: READ_WRITE,
  storeCustomer: READ_WRITE_DELETE,
  storeOrder: [...READ_WRITE_DELETE, "manage"],
  ssoProvider: [],
  ssoLoginEvent: [],
  heatmapSite: READ_WRITE_DELETE,
  heatmapPage: READ_WRITE_DELETE,
  heatmapEvent: READ_ONLY,
  sessionRecording: READ_WRITE_DELETE,
  flow: READ_WRITE_DELETE,
  flowRun: [...READ_WRITE_DELETE, "manage"],
  flowApproval: [...READ_ONLY, "manage"],
  creatorApp: READ_WRITE_DELETE,
  creatorRecord: READ_WRITE_DELETE,
  writerDoc: READ_WRITE_DELETE,
  sheet: READ_WRITE_DELETE,
  presentation: READ_WRITE_DELETE,
  kbArticle: READ_WRITE_DELETE,
  gantt: READ_WRITE_DELETE,
  timeEntry: READ_WRITE_DELETE,
  careerSite: READ_WRITE,
  "settings.workspace": [],
  "settings.users": [],
  "settings.billing": [],
  "settings.security": [],
  "settings.apiKeys": [],
  "settings.webhooks": [],
};

/** Viewer: read-only across the suite. */
const viewerMatrix: RoleMatrix = Object.fromEntries(
  RESOURCES.map((r) => [
    r,
    r.startsWith("settings.") || r === "auditLog" ? [] : READ_ONLY,
  ]),
) as RoleMatrix;

export const ROLE_MATRIX: Record<SystemRole, RoleMatrix> = {
  OWNER: ownerMatrix,
  ADMIN: adminMatrix,
  MANAGER: managerMatrix,
  SALES: salesMatrix,
  FINANCE: financeMatrix,
  AGENT: agentMatrix,
  MEMBER: memberMatrix,
  VIEWER: viewerMatrix,
};

/** Pure check — no side effects, safe to call from anywhere. */
export function can(role: SystemRole, resource: Resource, action: Action): boolean {
  return ROLE_MATRIX[role][resource]?.includes(action) ?? false;
}

export class PermissionError extends Error {
  constructor(public resource: Resource, public action: Action, public role: SystemRole) {
    super(`Forbidden: ${role} cannot ${action} ${resource}`);
    this.name = "PermissionError";
  }
}

/** Throws PermissionError if the role lacks the permission. */
export function assertCan(role: SystemRole, resource: Resource, action: Action): void {
  if (!can(role, resource, action)) {
    throw new PermissionError(resource, action, role);
  }
}
